apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: checkov-project
  labels:
    app: flask
    delete: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flask
          image: fabiopalazzii/kubernetes-sample:flask@sha256:981cbc55b174144da6860d00eb7b7258fb076e26dcdeeb9ed3cb4db8aff1788e
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: checkov-project
          securityContext: 
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "0.5"
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 200Mi
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
