apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: checkov-project
  labels:
    app: flask
    delete: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: fabiopalazzii/kubernetes-sample:flask@sha256:d49d17d9220849ea7f9e7bf9b87fde2802f87be5e7e87b143a2867a7c4469bbd
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
