apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: checkov-project
  labels:
    app: flask
    delete: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: fabiopalazzii/kubernetes-sample:flask@sha256:91046688d7e1d66166ef35cbdbd8fad2ebfad019acbb936876449dc86864b1bb
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          imagePullPolicy: Always
          resources:
            limits:
              memory: "400Mi"
              cpu: "0.4"
            requests:
              memory: "200Mi"
              cpu: "0.2"
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
