apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
    delete: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: fabiopalazzii/kubernetes-sample:flask@sha256:9c26d86f707ad94053144227aba4ce16bb68f16679226a7fd82ffa58718b2962
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
