apiVersion: v1
kind: Service
metadata:
  name: flask-lb
  namespace: checkov-project
  labels:
    delete: "true"
spec:
  selector:
    app: flask
  ports:
    - port: 8080
      targetPort: 5000
  type: LoadBalancer