apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: checkov-project
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flask
          image: fabiopalazzii/kubernetes-sample:flask@sha256:4394d579c47383832d1a1b57342993eefcab53411cdf39b9f94dab6000886442
          env:
            - name: NAMESPACE
              value: checkov-project
          securityContext: 
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          imagePullPolicy: Always
          resources:
            limits:
              memory: "400Mi"
              cpu: "0.4"
            requests:
              memory: "200Mi"
              cpu: "0.2"
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
