apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: checkov-project
  labels:
    name: mongo
    delete: "true"
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo