apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  externalTrafficPolicy: "Local"
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  type: NodePort
status:
  loadBalancer: {}