apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: checkov-project
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql